/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.izzettinozmen.riskgame;

/**
 *
 * @author ifozmen
 */
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Color;

public class ClientGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonAfghanistan = new javax.swing.JButton();
        buttonIrkutsk = new javax.swing.JButton();
        buttonYakutsk = new javax.swing.JButton();
        buttonJapan = new javax.swing.JButton();
        buttonKamchatka1 = new javax.swing.JButton();
        buttonChina = new javax.swing.JButton();
        buttonSiberia = new javax.swing.JButton();
        buttonIndia = new javax.swing.JButton();
        buttonMiddleEast = new javax.swing.JButton();
        buttonUkranie = new javax.swing.JButton();
        buttonSouthernEurope = new javax.swing.JButton();
        buttonUral = new javax.swing.JButton();
        buttonGreatBritain = new javax.swing.JButton();
        buttonEgypt = new javax.swing.JButton();
        buttonWesternEurope = new javax.swing.JButton();
        buttonNorthAfrica = new javax.swing.JButton();
        buttonCongo = new javax.swing.JButton();
        buttonNorthernEurope = new javax.swing.JButton();
        buttonSouthAfrica = new javax.swing.JButton();
        buttonWesternAustralia = new javax.swing.JButton();
        buttonLatifland = new javax.swing.JButton();
        buttonSametistan = new javax.swing.JButton();
        buttonEastAfrica = new javax.swing.JButton();
        buttonIndonesia = new javax.swing.JButton();
        buttonNewGuinea = new javax.swing.JButton();
        buttonPeru = new javax.swing.JButton();
        buttonSlam = new javax.swing.JButton();
        buttonArgentina = new javax.swing.JButton();
        buttonVenezuela = new javax.swing.JButton();
        buttonEasternUnitedStates = new javax.swing.JButton();
        buttonCentralAmerica = new javax.swing.JButton();
        buttonAlberta = new javax.swing.JButton();
        buttonBrazil = new javax.swing.JButton();
        buttonOntario = new javax.swing.JButton();
        buttonQuebec = new javax.swing.JButton();
        buttonNorthWestTerritory = new javax.swing.JButton();
        buttonAratopia = new javax.swing.JButton();
        buttonAlaska = new javax.swing.JButton();
        buttonGreenland = new javax.swing.JButton();
        buttonCihanland = new javax.swing.JButton();
        buttonIzzettinia = new javax.swing.JButton();
        buttonWesternUnitedStates = new javax.swing.JButton();
        buttonMongolia = new javax.swing.JButton();
        buttonScandinavia = new javax.swing.JButton();
        buttonIceland = new javax.swing.JButton();
        buttonEasternAustralia1 = new javax.swing.JButton();
        labelMapImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareaWarLogs = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        buttonFinishTurn = new javax.swing.JButton();
        buttonSurrender = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelCurrentPlayingPlayerUI = new javax.swing.JLabel();
        labelCurrentPlayerSoldierNumberUI = new javax.swing.JLabel();
        labelCurrentPlayerTerritoryNumberUI = new javax.swing.JLabel();
        PlayerName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelPlayerSoldierNumberUI = new javax.swing.JLabel();
        labelPlayerTerritoryNumberUI = new javax.swing.JLabel();
        labelPlayerEarnedSoldierPerTurnUI = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buttonLeaveGame1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonAfghanistan.setText("0");
        jPanel1.add(buttonAfghanistan, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, -1, -1));

        buttonIrkutsk.setText("0");
        jPanel1.add(buttonIrkutsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, -1, -1));

        buttonYakutsk.setText("0");
        jPanel1.add(buttonYakutsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 130, -1, -1));

        buttonJapan.setText("0");
        jPanel1.add(buttonJapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 270, -1, -1));

        buttonKamchatka1.setText("0");
        jPanel1.add(buttonKamchatka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 130, -1, -1));

        buttonChina.setText("0");
        jPanel1.add(buttonChina, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, -1, -1));

        buttonSiberia.setText("0");
        jPanel1.add(buttonSiberia, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, -1, -1));

        buttonIndia.setText("0");
        jPanel1.add(buttonIndia, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, -1, -1));

        buttonMiddleEast.setText("0");
        jPanel1.add(buttonMiddleEast, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, -1, -1));

        buttonUkranie.setText("0");
        jPanel1.add(buttonUkranie, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        buttonSouthernEurope.setText("0");
        jPanel1.add(buttonSouthernEurope, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, -1));

        buttonUral.setText("0");
        jPanel1.add(buttonUral, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, -1, -1));

        buttonGreatBritain.setText("0");
        jPanel1.add(buttonGreatBritain, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        buttonEgypt.setText("0");
        jPanel1.add(buttonEgypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        buttonWesternEurope.setText("0");
        jPanel1.add(buttonWesternEurope, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        buttonNorthAfrica.setText("0");
        jPanel1.add(buttonNorthAfrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        buttonCongo.setText("0");
        jPanel1.add(buttonCongo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        buttonNorthernEurope.setText("0");
        jPanel1.add(buttonNorthernEurope, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        buttonSouthAfrica.setText("0");
        jPanel1.add(buttonSouthAfrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, -1, -1));

        buttonWesternAustralia.setText("0");
        jPanel1.add(buttonWesternAustralia, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 580, -1, -1));

        buttonLatifland.setText("0");
        jPanel1.add(buttonLatifland, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 600, -1, -1));

        buttonSametistan.setText("0");
        jPanel1.add(buttonSametistan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 390, -1, -1));

        buttonEastAfrica.setText("0");
        jPanel1.add(buttonEastAfrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, -1));

        buttonIndonesia.setText("0");
        jPanel1.add(buttonIndonesia, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 470, -1, -1));

        buttonNewGuinea.setText("0");
        jPanel1.add(buttonNewGuinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 490, -1, -1));

        buttonPeru.setText("0");
        buttonPeru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPeruActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPeru, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        buttonSlam.setText("0");
        jPanel1.add(buttonSlam, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 390, -1, -1));

        buttonArgentina.setText("0");
        jPanel1.add(buttonArgentina, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, -1, -1));

        buttonVenezuela.setText("0");
        jPanel1.add(buttonVenezuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        buttonEasternUnitedStates.setText("0");
        jPanel1.add(buttonEasternUnitedStates, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        buttonCentralAmerica.setText("0");
        jPanel1.add(buttonCentralAmerica, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        buttonAlberta.setText("0");
        jPanel1.add(buttonAlberta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        buttonBrazil.setText("0");
        jPanel1.add(buttonBrazil, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        buttonOntario.setText("0");
        jPanel1.add(buttonOntario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        buttonQuebec.setText("0");
        jPanel1.add(buttonQuebec, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        buttonNorthWestTerritory.setText("0");
        jPanel1.add(buttonNorthWestTerritory, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        buttonAratopia.setText("0");
        buttonAratopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAratopiaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAratopia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        buttonAlaska.setText("0");
        jPanel1.add(buttonAlaska, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        buttonGreenland.setText("0");
        jPanel1.add(buttonGreenland, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        buttonCihanland.setText("0");
        jPanel1.add(buttonCihanland, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        buttonIzzettinia.setText("0");
        jPanel1.add(buttonIzzettinia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        buttonWesternUnitedStates.setText("0");
        jPanel1.add(buttonWesternUnitedStates, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        buttonMongolia.setText("0");
        buttonMongolia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMongoliaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonMongolia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, -1, -1));

        buttonScandinavia.setText("0");
        jPanel1.add(buttonScandinavia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        buttonIceland.setText("0");
        jPanel1.add(buttonIceland, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        buttonEasternAustralia1.setText("0");
        jPanel1.add(buttonEasternAustralia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 580, -1, -1));

        labelMapImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/izzettinozmen/riskgame/resources/riskMap_small.jpg"))); // NOI18N
        jPanel1.add(labelMapImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 730));

        textareaWarLogs.setColumns(20);
        textareaWarLogs.setRows(5);
        jScrollPane1.setViewportView(textareaWarLogs);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("War Logs");

        buttonFinishTurn.setText("Finish Turn");
        buttonFinishTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinishTurnActionPerformed(evt);
            }
        });

        buttonSurrender.setText("Surrender");
        buttonSurrender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSurrenderActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Player Turn:");

        jLabel10.setText("Total Soldiers:");

        jLabel11.setText("Territories");

        labelCurrentPlayingPlayerUI.setText("Player");

        labelCurrentPlayerSoldierNumberUI.setText("Player");

        labelCurrentPlayerTerritoryNumberUI.setText("Player");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCurrentPlayingPlayerUI))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCurrentPlayerSoldierNumberUI))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCurrentPlayerTerritoryNumberUI)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelCurrentPlayingPlayerUI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelCurrentPlayerSoldierNumberUI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelCurrentPlayerTerritoryNumberUI))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        PlayerName.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        PlayerName.setText("Player");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/izzettinozmen/riskgame/resources/Riskgame_logosmall.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel12.setText("Game State:");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Your Soldiers:");

        jLabel15.setText("Your Territories:");

        jLabel16.setText("Soldier Per Turn:");

        labelPlayerSoldierNumberUI.setText("0");

        labelPlayerTerritoryNumberUI.setText("0");

        labelPlayerEarnedSoldierPerTurnUI.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPlayerSoldierNumberUI))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPlayerTerritoryNumberUI))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPlayerEarnedSoldierPerTurnUI)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(labelPlayerSoldierNumberUI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(labelPlayerTerritoryNumberUI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(labelPlayerEarnedSoldierPerTurnUI))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel13.setText("STANDBY");

        buttonLeaveGame1.setText("Leave");
        buttonLeaveGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLeaveGame1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonFinishTurn)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSurrender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonLeaveGame1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(PlayerName)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(PlayerName)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonFinishTurn)
                            .addComponent(buttonSurrender)
                            .addComponent(buttonLeaveGame1))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPeruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPeruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPeruActionPerformed

    private void buttonMongoliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMongoliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMongoliaActionPerformed

    private void buttonAratopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAratopiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAratopiaActionPerformed

    private void buttonSurrenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSurrenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSurrenderActionPerformed

    private void buttonLeaveGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLeaveGame1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLeaveGame1ActionPerformed

    private void buttonFinishTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinishTurnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFinishTurnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MacOS".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlayerName;
    private javax.swing.JButton buttonAfghanistan;
    private javax.swing.JButton buttonAlaska;
    private javax.swing.JButton buttonAlberta;
    private javax.swing.JButton buttonAratopia;
    private javax.swing.JButton buttonArgentina;
    private javax.swing.JButton buttonBrazil;
    private javax.swing.JButton buttonCentralAmerica;
    private javax.swing.JButton buttonChina;
    private javax.swing.JButton buttonCihanland;
    private javax.swing.JButton buttonCongo;
    private javax.swing.JButton buttonEastAfrica;
    private javax.swing.JButton buttonEasternAustralia1;
    private javax.swing.JButton buttonEasternUnitedStates;
    private javax.swing.JButton buttonEgypt;
    private javax.swing.JButton buttonFinishTurn;
    private javax.swing.JButton buttonGreatBritain;
    private javax.swing.JButton buttonGreenland;
    private javax.swing.JButton buttonIceland;
    private javax.swing.JButton buttonIndia;
    private javax.swing.JButton buttonIndonesia;
    private javax.swing.JButton buttonIrkutsk;
    private javax.swing.JButton buttonIzzettinia;
    private javax.swing.JButton buttonJapan;
    private javax.swing.JButton buttonKamchatka1;
    private javax.swing.JButton buttonLatifland;
    private javax.swing.JButton buttonLeaveGame1;
    private javax.swing.JButton buttonMiddleEast;
    private javax.swing.JButton buttonMongolia;
    private javax.swing.JButton buttonNewGuinea;
    private javax.swing.JButton buttonNorthAfrica;
    private javax.swing.JButton buttonNorthWestTerritory;
    private javax.swing.JButton buttonNorthernEurope;
    private javax.swing.JButton buttonOntario;
    private javax.swing.JButton buttonPeru;
    private javax.swing.JButton buttonQuebec;
    private javax.swing.JButton buttonSametistan;
    private javax.swing.JButton buttonScandinavia;
    private javax.swing.JButton buttonSiberia;
    private javax.swing.JButton buttonSlam;
    private javax.swing.JButton buttonSouthAfrica;
    private javax.swing.JButton buttonSouthernEurope;
    private javax.swing.JButton buttonSurrender;
    private javax.swing.JButton buttonUkranie;
    private javax.swing.JButton buttonUral;
    private javax.swing.JButton buttonVenezuela;
    private javax.swing.JButton buttonWesternAustralia;
    private javax.swing.JButton buttonWesternEurope;
    private javax.swing.JButton buttonWesternUnitedStates;
    private javax.swing.JButton buttonYakutsk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCurrentPlayerSoldierNumberUI;
    private javax.swing.JLabel labelCurrentPlayerTerritoryNumberUI;
    private javax.swing.JLabel labelCurrentPlayingPlayerUI;
    private javax.swing.JLabel labelMapImage;
    private javax.swing.JLabel labelPlayerEarnedSoldierPerTurnUI;
    private javax.swing.JLabel labelPlayerSoldierNumberUI;
    private javax.swing.JLabel labelPlayerTerritoryNumberUI;
    private javax.swing.JTextArea textareaWarLogs;
    // End of variables declaration//GEN-END:variables
}
