/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.izzettinozmen.riskgame;

import javax.swing.JOptionPane;

/**
 *
 * @author ifozmen
 */
public class StartScreen extends javax.swing.JFrame {
    private Client client;
    private String playerName;

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        this(null);
    }

    public StartScreen(String playerName) {
        this.playerName = playerName;
        initComponents();
        setLocationRelativeTo(null);
        if (this.playerName == null || this.playerName.trim().isEmpty()) {
            askPlayerName();
        } else {
            buttonHostGame.setEnabled(true);
            buttonJoinGame.setEnabled(true);
            client = new Client(this.playerName.trim());
        }
    }

    private void askPlayerName() {
        buttonHostGame.setEnabled(false);
        buttonJoinGame.setEnabled(false);
        while (playerName == null || playerName.trim().isEmpty()) {
            playerName = JOptionPane.showInputDialog(this, "Lütfen bir oyuncu adı girin:", "Oyuncu Adı", JOptionPane.PLAIN_MESSAGE);
            if (playerName == null) {
                // Kullanıcı iptal ederse uygulamadan çık
                System.exit(0);
            }
            if (playerName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Oyuncu adı boş olamaz!", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
        buttonHostGame.setEnabled(true);
        buttonJoinGame.setEnabled(true);
        client = new Client(playerName.trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonHostGame = new javax.swing.JButton();
        buttonJoinGame = new javax.swing.JButton();
        buttonExitGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonHostGame.setText("Host Game");
        buttonHostGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHostGameActionPerformed(evt);
            }
        });
        getContentPane().add(buttonHostGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 163, 35));

        buttonJoinGame.setText("Join Game");
        buttonJoinGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJoinGameActionPerformed(evt);
            }
        });
        getContentPane().add(buttonJoinGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 164, 35));

        buttonExitGame.setText("Exit Game");
        buttonExitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitGameActionPerformed(evt);
            }
        });
        getContentPane().add(buttonExitGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 163, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/izzettinozmen/riskgame/resources/Riskgame_logosmall.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/izzettinozmen/riskgame/resources/riskBG.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHostGameActionPerformed(java.awt.event.ActionEvent evt) {
        if (client.connect()) {
            if (client.createLobby()) {
                GameLobbyHost lobbyHost = new GameLobbyHost(client);
                lobbyHost.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                    "A game lobby already exists!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                "Could not connect to server!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buttonJoinGameActionPerformed(java.awt.event.ActionEvent evt) {
        if (client.connect()) {
            if (client.joinLobby()) {
                GameLobbyPlayer lobbyPlayer = new GameLobbyPlayer(client);
                lobbyPlayer.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                    "No game lobby available!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                "Could not connect to server!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buttonExitGameActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExitGame;
    private javax.swing.JButton buttonHostGame;
    private javax.swing.JButton buttonJoinGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
